### ISSUE TITLE
Link to Playground broken

### ISSUE THREAD

**Issue by marcus-castro-sp** [OfficeDev/microsoft-teams-ui-component-library#136] opened 2022-05-19 16:19 UTC
Hi there,

The link for the Playground on the README file seems to be incorrect. It's redirecting me to: "https://dev.teams.microsoft.com/storybook/main/index.html", which gives the following error message:

![image](https://user-images.githubusercontent.com/65231173/169349175-506e7d10-bf29-4d5b-a322-308df508ee29.png)

![image](https://user-images.githubusercontent.com/65231173/169348987-3d8e64e5-3e23-4761-9f1f-1e3617742adb.png)

**Comment by thure** [comment] 2022-05-20 04:06
It was taken down for security reasons, apologies for the inconvenience. It'll be back soon.

**Comment by thure** [comment] 2022-05-20 04:17
This is a duplicate of #129.

**Closed by thure** 2022-05-20 04:17 UTC
Labels: bug

**Comment by thure** [comment] 2022-05-26 20:48
This and its duplicate are now resolved :)
